"""Shared content-type-specific action selection rules.

These rules define which actions the LLM must generate for each document type
(fiction, medical, problem documents, language learning, etc.). They apply
identically to welcome-message suggestions (shared.describe) and to the
assistant answer buttons (shared.prompts.labels_actions).

Updating rules here propagates automatically to all consumers.
"""

ACTION_CONTENT_TYPES_PL = r"""Obowiązkowe akcje dla typów treści:
- POWIEŚĆ/BELETRYSTYKA → użyj prawdziwego imienia i nazwiska autora (nigdy nawiasów zastępczych). Zróżnicuj wording — wybierz jedno z: "Napisz nowy inspirowany rozdział w stylu IMIĘ ✏️", "Stwórz stronę w stylu IMIĘ ✏️", "Improwizuj scenę jak IMIĘ ✏️", "Napisz nowy rozdział inspirowany IMIĘ ✏️". Np. jeśli autorem jest Rumi: "Napisz nowy inspirowany rozdział w stylu Rumiego ✏️" — NIE "[Rumi]" ani "[Imię Nazwisko autora]".
- POEZJA/FILOZOFIA/CYTATY → użyj prawdziwego imienia autora. Zróżnicuj: "Napisz nowy inspirowany wiersz w stylu IMIĘ 📜", "Skomponuj strofę w duchu IMIĘ 📜", "Stwórz wiersz głosem IMIĘ 📜". DODATKOWO dodaj akcję cytatową jako osobny prompt (najlepiej do „More ...“): "Napisz nowy inspirowany cytat w stylu IMIĘ 💬".
- PORADNIK/SAMOROZWÓJ → użyj prawdziwego imienia autora. Losowo jedno z: "Napisz 10 nowych wskazówek inspirowanych IMIĘ 💡", "Stwórz 7 ćwiczeń inspirowanych IMIĘ 🏋️", "Wygeneruj 12 pytań refleksyjnych inspirowanych IMIĘ 🤔", "Napisz 5 scenariuszy z życia inspirowanych IMIĘ 🎭", "Stwórz 14-dniowy plan działania inspirowany IMIĘ 📅"
- ZDJĘCIE JEDZENIA / POSIŁEK (zdjęcie pokazuje jedzenie, dania, składniki, tacę z jedzeniem, talerz restauracyjny, stołówkę, bufet, przekąski, zupę lub jakikolwiek przygotowany/podany posiłek) → OBOWIĄZKOWO: dołącz "Stwórz przepis inspirowany: [tytuł zdjęcia] 🍳" jako jeden z pierwszych 2 przycisków akcji. Podstaw [tytuł zdjęcia] z nagłówka „# Tytuł" (np. "Stwórz przepis inspirowany: Posiłek w Kafeterii 🍳"). Zabrania się używania TYLKO "Stwórz przepis" bez tytułu.
- EBOOK / MINIBOOK / PODRĘCZNIK / PRZEWODNIK O KONKRETNYM TEMACIE (np. minibook o granicach, ebook o żywieniu, podręcznik psychologii, przewodnik po ogrodnictwie) → OBOWIĄZKOWO jako 3. akcja (zaraz po "Wygeneruj obraz…" i "Napisz nowy inspirowany rozdział…") DODAJ: "Stwórz quiz z najważniejszych faktów 🧠". Quiz sprawdza wiedzę i jest naturalnym sposobem nauki z ebooka o danym temacie.
  Przykład dla "Minibook o granicach" Matyldy Kozakiewicz: 4. "Wygeneruj obraz inspirowany: Minibook o granicach 🎨", 5. "Napisz nowy inspirowany rozdział w stylu Matyldy Kozakiewicz ✏️", 6. "Stwórz quiz z najważniejszych faktów 🧠".
- NAUKA JĘZYKA / PODRĘCZNIK JĘZYKOWY / MATERIAŁ DO NAUCZANIA JĘZYKA (podręcznik do angielskiego, kurs niemieckiego, gramatyka hiszpańska, słownictwo, ESL/EFL, TOEFL/IELTS, zeszyt ćwiczeń językowych) → NAJWYŻSZY PRIORYTET: quiz MUSI być PIERWSZĄ akcją, PRZED "Wygeneruj obraz…". Format: "Stwórz quiz z materiału 🧠" lub "Stwórz quiz ze słownictwa 🧠" albo "Stwórz quiz z gramatyki 🧠" — dopasuj do dokumentu. Quiz jest kluczowy dla utrwalenia i sprawdzenia wiedzy językowej.
- WYNIKI BADAŃ LAB / DOKUMENTY MEDYCZNE → użyj wyłącznie analitycznych promptów (ŻADNYCH kreatywnych fikcji): quiz z wiedzy medycznej 🧠, checklista do zrobienia 📋, tabela wyników z komentarzem 📊, podsumowanie kluczowych odchyleń 📝, FAQ: pytania do lekarza ❓, słownik pojęć medycznych 📖, oś czasu kolejnych kroków 📅, notatki do wizyty 📓, plan suplementacji 💊, analiza ryzyka sercowo-naczyniowego 📊, wykres trendów wyników 📈, lista badań do wykonania 🔬
  * Dodaj "Postaw diagnozę na podstawie wyników 🔬" TYLKO gdy dokument to FAKTYCZNIE wyniki badań konkretnego pacjenta (morfologia, TSH, lipidogram, wyniki laboratoryjne z wartościami i zakresami referencyjnymi). NIE dodawaj tej akcji dla ogólnych poradników medycznych, encyklopedii chorób, artykułów o zdrowiu — tylko dla prawdziwych wyników badań.
- DOKUMENTY PRAWNE / FINANSOWE / NAUKOWE / TECHNICZNE → użyj wyłącznie analitycznych promptów dopasowanych do dziedziny dokumentu (ŻADNYCH kreatywnych fikcji, ŻADNEJ diagnozy medycznej)
- DOKUMENTY PROBLEMOWE — pisma wymagające działania (wezwania do zapłaty, pisma urzędowe ZUS/US/NFZ/KRUS, nakazy zapłaty, decyzje administracyjne, pisma sądowe i komornicze, pisma windykacyjne, odmowy ubezpieczyciela, odwołania, spory pracownicze z pracodawcą, kary administracyjne, mandaty, pisma o odszkodowanie, wezwania do rejestracji/złożenia dokumentów, pisma o zaległości w płatnościach) → wygeneruj WYŁĄCZNIE pytania i akcje ukierunkowane na ROZWIĄZANIE PROBLEMU.
  ZABRONIONE dla tych dokumentów: quiz, wiersz, bajka, obraz, fikcja, piosenka, kreatywna twórczość, rozrywka.
  Naturalne pytania (bez emoji) — MUSZĄ dotyczyć: kto żąda i czego, termin na odpowiedź lub działanie, wymagane dokumenty i dowody, konsekwencje braku działania, prawa użytkownika w tej sytuacji, organ/osoba/firma do kontaktu, możliwe sposoby odwołania lub negocjacji.
  Przykładowe naturalne pytania: "Jaki jest termin na odpowiedź?", "Co dokładnie muszę złożyć w ZUS?", "Czy mogę odwołać się od tej decyzji?", "Jakie konsekwencje grożą za brak reakcji?", "Co zrobić, żeby zarejestrować się jako bezrobotny?", "Do jakiego urzędu/sądu muszę się zgłosić?"
  Akcje z emoji: "Lista kroków do rozwiązania problemu ✅", "Napisz odpowiedź na to pismo 📝", "Jakie mam prawa w tej sytuacji? ⚖️", "Zidentyfikuj kluczowe terminy i deadliny 🗓️", "Stwórz checklistę wymaganych dokumentów 📋", "Analiza konsekwencji braku reakcji ⚠️", "Plan działania krok po kroku 🚩", "Co mogę zakwestionować lub negocjować? 💬"
- Inne typy (WYŁĄCZNIE dla dokumentów kreatywnych/literackich/rozrywkowych — powieści, poezja, blogi, scenariusze) → dobierz kreatywne akcje wg priorytetu (wyżej = ważniejsze, dopasowanie kontekstowe jako czynnik dodatkowy): wygeneruj obraz 🎨, napisz nowy inspirowany rozdział ✏️, napisz nowy inspirowany wiersz 📜, bajka 🧚, napisz nowe cytaty 💬, quiz 🧠, checklista ✅, diagram mermaid 🖼️, podsumowanie 📝, oś czasu 📅, mapa myśli 🧩, fiszki 🃏, notatki do nauki 📓, FAQ ❓, prezentacja 📽️, wyjaśnij jak dla dziecka 👶, za i przeciw ⚖️, debata 💬, słownik pojęć 📖, post na social media 📱, recenzja ⭐, streszczenie wykonawcze 🎯, tabela porównawcza 📊, plan działania 🚩, szkic emaila 📧, list motywacyjny 💼, dialog 🎤, infografika 📊, piosenka 🎵, przetłumacz 🌍
- Nie zawsze wybieraj quiz — bądź kreatywny i zróżnicowany
"""

ACTION_CONTENT_TYPES_EN = r"""Mandatory actions for content types:
- NOVEL/FICTION → Use the actual author's name (never placeholder brackets). Vary the phrasing — pick one of: "Write a new chapter inspired by NAME ✏️", "Create a page in NAME's style ✏️", "Improvise a scene inspired by NAME ✏️". For example, if the author is Rumi write "Write a new chapter inspired by Rumi ✏️" — NOT "[Rumi]" or "[Author Full Name]".
- POETRY/PHILOSOPHY/QUOTES → Use the actual author's name. Vary among: "Write a new poem inspired by NAME 📜", "Compose a verse in NAME's spirit 📜", "Create a poem in NAME's voice 📜". Additionally include a dedicated quote action (preferably in "More ..."): "Write a new quote inspired by NAME 💬".
- SELF-HELP/GUIDE → Use the real author name. Randomly pick one of: "Write 10 new tips inspired by NAME 💡", "Create 7 exercises inspired by NAME 🏋️", "Generate 12 reflection questions inspired by NAME 🤔", "Draft 5 real-life scenarios inspired by NAME 🎭", "Build a 14-day action plan inspired by NAME 📅"
- FOOD / MEAL PHOTO (image shows food, dishes, ingredients, meal tray, restaurant plate, cafeteria, buffet, snacks, soup, or any prepared/plated food) → MANDATORY: include "Create a recipe inspired by [image title] 🍳" as one of the first 2 action prompts. Substitute [image title] with the actual title from the "# Title" heading (e.g. "Create a recipe inspired by Cafeteria Meal Tray 🍳"). Never use bare "Create recipe" without the title.
- EBOOK / MINI-BOOK / TEXTBOOK / GUIDE ABOUT A SUBJECT (e.g. a minibook on healthy boundaries, ebook on nutrition, psychology textbook, beginner's gardening guide) → MANDATORY: as the 3rd action (right after "Generate an image…" and "Write a new chapter inspired by…") INCLUDE "Create a quiz from the key facts 🧠". A quiz checks comprehension and is the most natural way to learn from a subject-matter ebook.
  Example for "Minibook o granicach" by Matylda Kozakiewicz: 4. "Generate an image inspired by: Minibook about boundaries 🎨", 5. "Write a new chapter inspired by Matylda Kozakiewicz ✏️", 6. "Create a quiz from the key facts 🧠".
- LANGUAGE LEARNING / TEACHING MATERIAL (English grammar book, Spanish course, German vocabulary workbook, ESL/EFL/TOEFL/IELTS prep, language-learning textbook) → HIGHEST PRIORITY: a quiz MUST be the FIRST action, BEFORE "Generate image…". Format: "Create a quiz from the material 🧠" or "Create a vocabulary quiz 🧠" or "Create a grammar quiz 🧠" — fit it to the document. Quizzes are essential for language retention and self-check.
- LAB TEST / MEDICAL DOCUMENTS → use ONLY analytical prompts (NO creative fiction): medical knowledge quiz 🧠, action checklist 📋, results table with commentary 📊, key deviations summary 📝, FAQ: questions for the doctor ❓, medical glossary 📖, next-steps timeline 📅, visit notes 📓, supplementation plan 💊, cardiovascular risk analysis 📊, results trend chart 📈, list of tests to run 🔬
  * Add "Make a diagnosis based on results 🔬" ONLY when the document is GENUINELY lab test results for a specific patient (CBC, TSH, lipid panel, blood test values with reference ranges). Do NOT add this action for general medical guides, disease encyclopedias, health articles — only for actual patient test results.
- LEGAL / FINANCIAL / SCIENTIFIC / TECHNICAL DOCUMENTS → use ONLY domain-appropriate analytical prompts (NO creative fiction, NO medical diagnosis)
- PROBLEM DOCUMENTS — documents requiring action (payment demands, official government letters from social security/tax authority/health insurance, court orders, administrative decisions, debt collection letters, insurance denials, appeal documents, workplace disputes, fines, penalty notices, compensation claims, summons to register or submit documents, notices of overdue payments) → generate ONLY questions and actions focused on SOLVING THE PROBLEM.
  PROHIBITED for these documents: quiz, poem, fairy tale, image generation, fiction, song, creative content, entertainment.
  Natural questions (NO emoji) — MUST cover: who is demanding what, deadline for response or action, required documents and evidence, consequences of inaction, user's rights in this situation, who/which office/company to contact, possible ways to appeal or negotiate.
  Example natural questions: "What is the deadline to respond?", "What documents do I need to submit?", "Can I appeal this decision?", "What happens if I don't respond?", "What are my rights here?", "Which office do I need to contact?", "How do I register as unemployed?", "What proof of health insurance do I need to provide?"
  Action prompts with emoji: "Step-by-step action plan ✅", "Draft a response letter to this notice 📝", "What are my rights in this situation? ⚖️", "Identify key deadlines and due dates 🗓️", "Checklist of required documents 📋", "Consequences of not responding ⚠️", "Action plan: what to do first 🚩", "What can I dispute or negotiate? 💬"
- Other types (ONLY for creative/literary/entertainment documents — novels, poetry, blogs, screenplays) → pick creative actions by priority (higher = more important, context fit as secondary factor): generate image 🎨, write a new chapter inspired by ✏️, write a new poem inspired by 📜, fairy tale 🧚, write new quotes inspired by 💬, quiz 🧠, checklist ✅, mermaid diagram 🖼️, summary 📝, timeline 📅, mind map 🧩, flashcards 🃏, study notes 📓, FAQ ❓, presentation 📽️, explain like I'm 5 👶, pros & cons ⚖️, debate 💬, glossary 📖, social media post 📱, review ⭐, executive summary 🎯, comparison table 📊, action plan 🚩, email draft 📧, cover letter 💼, dialogue 🎤, infographic 📊, song 🎵, translate 🌍
- Do NOT always pick quiz — be creative and varied
"""
