/**
 * Auto-generation of companion images for "inspired" creative-writing answers.
 *
 * When the user asks the model to "write inspired chapter / poem / story / ..."
 * and the LLM produces a substantial piece of text, we roll a coin and — on
 * success — kick off a background image-generation call that paints a picture
 * inspired by the same prompt. The image is then appended to the assistant
 * message's content so the frontend picks it up on its next poll.
 */

// Loose detector: matches phrases like "write inspired chapter",
// "inspired poem like Paulo Coelho", "draft a fairy tale inspired by ...", etc.
// We keep it intentionally permissive so the model's own action labels
// (e.g. "Write inspired chapter like Stephen King ✏️") are covered, while
// still requiring the "inspired" keyword to avoid false positives on
// ordinary Q&A traffic.
const INSPIRED_CREATIVE_RE =
  /\binspired\b[^\n]{0,80}?\b(chapter|poem|poet|story|stories|tale|fairy|song|lyric|essay|monologue|scene|parable|short\s+story)\b|\b(chapter|poem|poet|story|tale|fairy|song|lyric|essay|monologue|scene|parable)s?\b[^\n]{0,80}?\binspired\b/i

// Only auto-generate when the answer is clearly a "large chunk of text".
// Creative chapters/poems usually blow well past this threshold; short
// clarifying answers stay image-free.
const MIN_ANSWER_LENGTH = 600

export function isInspiredCreativeQuestion(question: string): boolean {
  return INSPIRED_CREATIVE_RE.test(question)
}

export function shouldAutoGenerateImage(
  question: string,
  answer: string,
  probability = 0.5,
  random: () => number = Math.random,
): boolean {
  if (!isInspiredCreativeQuestion(question)) return false
  if ((answer || '').length < MIN_ANSWER_LENGTH) return false
  return random() < probability
}

// Keep the prompt payload bounded so the Python side doesn't choke on huge
// inputs and OpenAI stays within context limits.
const MAX_ANSWER_SNIPPET = 1500

export function buildAutoImageQuestion(userQuestion: string, answer: string): string {
  const trimmed = (answer || '').slice(0, MAX_ANSWER_SNIPPET).trim()
  if (!trimmed) return userQuestion
  return `${userQuestion}\n\n---\n\n${trimmed}`
}

export type ImageCitation = {
  fileName: string
  chunkId: string
  text: string
  section?: string | null
  page?: number | null
}

export type AutoImageResult = {
  fileName: string
  imageUrl: string
  imageTitle: string
  imagePrompt: string
  revisedPrompt?: string
  imageSources: ImageCitation[]
}

/**
 * Compose the markdown + HTML snippet that gets appended to the assistant
 * message. Mirrors the look of the dedicated /generate-image route
 * (image + caption with quoted title + source markers), and tacks on a
 * small "generated image" sublabel so users know it was auto-produced.
 *
 * Source markers are offset by the number of citations already present in
 * the original answer so the `[N]` indices line up with the combined
 * citations array the frontend receives.
 */
export function renderAutoImageMarkdown(
  result: AutoImageResult,
  originalCitationsCount: number,
): string {
  const markers = result.imageSources.length
    ? ' ' +
      result.imageSources
        .map((_, i) => `[${originalCitationsCount + i + 1}]`)
        .join('')
    : ''
  return (
    `\n\n![${result.imageTitle}](${result.imageUrl})\n` +
    `<p class="image-caption">"${result.imageTitle}"${markers}</p>\n` +
    `<p class="image-caption-sublabel">generated image</p>`
  )
}

/**
 * Merge the existing assistant citations (plain array) with the new image
 * sources into a hybrid object that also carries image metadata for the
 * chat-history builder and downstream consumers.
 */
export function mergeCitationsWithImage(
  originalCitations: unknown,
  result: AutoImageResult,
): {
  citations: unknown[]
  _imageSources: ImageCitation[]
  _generatedImageDescription: string
  _autoGeneratedImage: true
} {
  const base = Array.isArray(originalCitations) ? originalCitations : []
  return {
    citations: base,
    _imageSources: result.imageSources,
    _generatedImageDescription: result.revisedPrompt || result.imagePrompt,
    _autoGeneratedImage: true,
  }
}
